### PR TITLE
Work in progress (wip): updating tests

### PR DESCRIPTION
**Pull request by mtoub**
- [ ] Feature
- [ ] Fix
- [x] Enhancement

## Brief
- Migrated from `npm` to `pnpm`
- Installed hardhat
- Configured `hardhat.config.ts`
- Added more scripts to `package.json`
- Updated tests
- Created a GitHub Action for testing

## Description
This branch tries to improve the deployment and testing environment by setting and using hardhat and rewriting the tests.

## Requirements :
:warning: Requires installing `pnpm`:
```bash
npm install pnpm
```
Then installing dependencies:
```bash
pnpm install
```

### CODE REVIEW

**Comment by guenoledc** [comment]
@mtoub is your intention to first adjust the dev framework before incorporating the diamond structure ?

**Comment by mtoub** [comment]
> @mtoub is your intention to first adjust the dev framework before incorporating the diamond structure ?

@guenoledc the idea is to integrate hardhat, refactor the testing code, and maybe discuss some improvement of this implementation to tackle the TODO's that you've mentioned in the solidity code. I suggest that we keep this base implementation in this repo as a reference and share the new Diamond-based so-bond implementation in another repo. We can then, use the same testing scripts for testing the so-bond implementation. What do you think?

**Comment by guenoledc** [comment]
@mtoub 

I see. But can I challenge a bit

You need to rework all test scripts and therefore how do we secure that the new tests are good enough. 

I was more thinking testing the diamond impl with the old testing scheme, then construct the hardhat refactoring. 

As discussed with Zak, it would be good to be able to do a end to end test with our internal software with the Diamond impl. 

But either way both stages should be done. 

Your thoughts?

**Comment by mtoub** [comment]
@guenoledc 

The new tests are the same as the old ones. What @ymaghzaz and I did, is that we tried using hardhat to refactor the code so that it can be easily adapted to run against the Diamond implementation. We can go through them together to make sure that they are compatible with the old ones.

Yes of course, we need to do an end-to-end testing with your software. In terms of interaction with the contract through your internal software, I think there will be no problem since we kept the same interfaces in the diamond implementation. The only thing that needs to be adapted is the deployment process, which will be different for the Diamond implementation. For that you can use the tooling that we are developing. 

As discussed last time, I started implementing the Coupon and Bilateral Trade factories with CREATE2. We will try to discuss it on Friday to see if it satisfies the whitelisting requirement. Then we can move forward into the testing phase.

How those this sounds for you?

**Comment by guenoledc** [comment]
@mtoub I have been doing some reading on hardhat and I have found implication for us (CACIB) to use this framework because it implies significant adjustments in our software since we base our solution on the `combined.json` file generated by the `solc --combined-json` option. Hardhat does not seem to compile and generate this output format.

Of course we could have both at the same time (hardhat + pure solc compilations).

I have never used hardhat before so it is going to take me a bit of time to get used to it ... any suggestion to speed up the learning process ?

**Comment by guenoledc** [comment]
I look into the hardhat plugins and seems pretty simple to generate the desired combine.json file from the artifacts.

so I have created the following plugin. Need to test it in my conventional software though. But for information for now.

```typescript


task("combined-json", "Generates a combined JSON file for all contracts", async (_, hre) => {
  console.log("Generating combined JSON file for all contracts...");
  const fqns = await hre.artifacts.getAllFullyQualifiedNames();

  if (fqns.length == 0) {
    console.log("No artifacts found. Please compile contracts first.");
    return;
  }

  // will receive an array of the different compiler versions used
  const versions: string[] = [];
  // will receive the JSON data for the combined.json file to be produced.
  // the structure of the file is:
  // - contracts:
  //  - <contract_fully_qualified_name>
  //    - abi
  //    - bin
  //    - bin-runtime
  // - version
  const combined: any = {contracts: {}}; 

  for (const fqn of fqns) {
    // skip the combined.json file itself
    if (fqn == ":combined") continue;
    // process the fqn of the smart contract compiled
    const bi = await hre.artifacts.getBuildInfo(fqn)
    if (bi && !versions.includes(bi.solcLongVersion)) {
      versions.push(bi.solcLongVersion);
    }
    const artifact = await hre.artifacts.readArtifact(fqn);
    combined.contracts[fqn] = {
      abi: artifact.abi,
      bin: artifact.bytecode == "0x" ? "" : artifact.bytecode,
      "bin-runtime": artifact.deployedBytecode == "0x" ? "" : artifact.deployedBytecode
    };
  }
  combined.version = versions.join(";");

  const fs = require("fs");
  const path = require("path");
  const location = path.join(hre.config.paths.artifacts, "combined.json");
  console.log("Generating", location)
  fs.writeFileSync(location, JSON.stringify(combined));
  console.log("Attention, other hardhat command may delete de combined.json file. Please, check it after running a command.");
  
})
```

**Comment by mtoub** [comment]
@guenoledc I have adapted and added the combined-json task in to the `hardhat.config.ts` file:
```
task("combined-json", "Generates a combined JSON file for all contracts")
  .addParam("output", "The output file name for the combined JSON file")
  .setAction(async (taskArgs, hre) => {
    console.log("Generating combined JSON file for all contracts...");
    const fqns = await hre.artifacts.getAllFullyQualifiedNames();

    if (fqns.length == 0) {
      console.log("No artifacts found. Please compile contracts first.");
      return;
    }

    // will receive an array of the different compiler versions used
    const versions: string[] = []; //[taskArgs.version];
    // will receive the JSON data for the combined.json file to be produced.
    // the structure of the file is:
    // - contracts:
    //  - <contract_fully_qualified_name>
    //    - abi
    //    - bin
    //    - bin-runtime
    // - version
    const combined: any = { contracts: {} };

    for (const fqn of fqns) {
      // skip the combined.json file itself
      if (fqn == ":combined") continue;
      // process the fqn of the smart contract compiled
      const bi = await hre.artifacts.getBuildInfo(fqn);
      if (bi && !versions.includes(bi.solcLongVersion)) {
        versions.push(bi.solcLongVersion);
      }
      const artifact = await hre.artifacts.readArtifact(fqn);
      combined.contracts[fqn] = {
        abi: artifact.abi,
        bin: stripHexPrefix(artifact.bytecode),
        "bin-runtime": stripHexPrefix(artifact.deployedBytecode),
      };
    }
    combined.version = versions.join(";");

    const fs = require("fs");
    const path = require("path");
    // use the output file name provided as a parameter
    const location = path.join(process.cwd(), taskArgs.output);
    console.log("Generating", location);
    fs.writeFileSync(location, JSON.stringify(combined), { flag: "w" });
    console.log(
      "Attention, other hardhat command may delete de combined.json file. Please, check it after running a command.",
    );
  });
```

I had to remove the `0x` from the `bin` and `bin-runtime` to match the `solc --combined-json` format. I have also added an `output` parameter to specify where the hardhat generated `combined.json` file is stored to avoid overwriting the solc one.

I have ran the hardhat `combined-json` against `solc --combined-json` (check scripts in `package.json`), the results are stored in `contract-artifacts/hardhat/combined.json` and `contract-artifacts/solc/combined.json`, respectively. 

I used the linux `diff` command to check the difference between the two files and stored that in [combined-diff.txt](https://github.com/FeverTokens/sc-bonds/blob/wip-updating-tests/combined-diff.txt) (N.B. prettier should be used to format the json files before running the `diff` command). It seems that both files have the same structure and produce the same abis, the only differences are the bytecodes which due the compiler and optimizer configuration in both solc and hardhat. I'll try to match the solidity versions and optimizer options to make the two files match.

**Comment by guenoledc** [comment]
Thanks 

It would be good to match the bytecode indeed because I tested the last compilation on the previous tests and it failed. I didn't yet had time to identify why it failed.

**Comment by guenoledc** [comment]
Hi @mtoub ,

So, I have resolved the original testing . it was coming from all the `register.grantXXXRole` that now consumes 116k gas instead of less than 100k gas before.  This is probably because of the use of `AccessControlEnumerable.sol` instead of `AccessControl.sol`. Not a big deal then.

So, now I feal we should try to replicate the so-bonds implementation with your Diamond impl. What do you think?

If we merge this branch we will replace the unit testing that are not completed yet with hardhat.

**Comment by mtoub** [comment]
@mtoub I have merged your pull request into this branch. 

I think we can manage to keep both tests. For the remaining test I'll try finishing them tonight. 

As per the diamond implementation I'll keep pushing to finalize it so that we can test it ASAP.

**Comment by guenoledc** [comment]
@mtoub , I think it is a good idea to keep both tests set for the moment. 
I will make a proposal to have both without making it too messy in the folders

**Comment by mtoub** [comment]
@guenoledc Great, I guess we can just create subfolders `test/solc` and `test/hardhat` same as we did with the `contracts-artifacts`. We'll see if we can keep some common utils function shared between the two.

**Comment by guenoledc** [comment]
@mtoub 

I wonder whether we should have 3 different repos. 
- One to keep the current impl   
- One with both tests solutions and  
- One repo for the diamond impl. 

This way the various impl can be tested with any test solution 

Of course this is a multi repo approach and one can prefer a mono repo approach with sub folders. 

Do you have a preference ?

**Comment by guenoledc** [comment]
Merging into a side branch to import into the refactoring branch

**Comment by mtoub** [comment]
> @mtoub
> 
> I wonder whether we should have 3 different repos.
> 
> * One to keep the current impl
> * One with both tests solutions and
> * One repo for the diamond impl.
> 
> This way the various impl can be tested with any test solution
> 
> Of course this is a multi repo approach and one can prefer a mono repo approach with sub folders.
> 
> Do you have a preference ?

@guenoledc having a monorepo doesn't sound do bad actually, that way we'll have everything in one place instead of confusing people and having the code scattered over multiple repos. 

@ymaghzaz do you think Turborepo can do the trick?

**Comment by guenoledc** [comment]
@mtoub @ymaghzaz 

I have started to refacto into a mono repo

When I have a 1st working setup i'll explain

**Pull request merged**
